apiVersion: v1
kind: Service
metadata:
  name: reuser-app
  namespace: reuser
spec:
  type: LoadBalancer
  selector:
    app: reuser-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
